name: Build & Push api gateway service Docker Image

on: 
  push:
    branches:
      - main
    paths:
      - 'api-gateway/**'

jobs:
  push_to_registry:
    name: Push Docker Image to Docker Hub   
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.USERNAME }}   
          password: ${{ secrets.PASSWORD }}   

      - name: Build and push docker image
        uses: docker/build-push-action@v4
        with:
          context: ./api-gateway/
          push: true
          tags: shihadb/ecommerce-api-service:latest
