name: Build & Push order service Docker Image

on: 
  push:
    branches:
      - main
    paths:
      - 'order-service/**'

jobs:
  push_to_registry:
    name: Push Docker Image to Docker Hub   
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.USERNAME }}   
          password: ${{ secrets.PASSWORD }}   

      - name: Build and push docker image
        uses: docker/build-push-action@v4
        with:
          context: ./order-service/
          push: true
          tags: shihadb/ecommerce-order-service:latest
